## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK100MHZ]

# Switches
#set_property PACKAGE_PIN V17 [get_ports {car[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[0]}]
#set_property PACKAGE_PIN V16 [get_ports {car[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[1]}]
#set_property PACKAGE_PIN W16 [get_ports {car[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[2]}]
#set_property PACKAGE_PIN W17 [get_ports {car[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[3]}]
#set_property PACKAGE_PIN W15 [get_ports {car[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[4]}]
#set_property PACKAGE_PIN V15 [get_ports {car[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[5]}]
#set_property PACKAGE_PIN W14 [get_ports {car[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[6]}]
#set_property PACKAGE_PIN W13 [get_ports {car[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[7]}]
#set_property PACKAGE_PIN V2 [get_ports {car[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[8]}]
#set_property PACKAGE_PIN T3 [get_ports {car[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[9]}]
#set_property PACKAGE_PIN T2 [get_ports {car[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[10]}]
#set_property PACKAGE_PIN R3 [get_ports {car[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[11]}]
#set_property PACKAGE_PIN W2 [get_ports {car[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[12]}]
#set_property PACKAGE_PIN U1 [get_ports {car[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[13]}]
#set_property PACKAGE_PIN T1 [get_ports {car[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {car[14]}]
#set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]


# LEDs
set_property PACKAGE_PIN U16 [get_ports {led}]
set_property IOSTANDARD LVCMOS33 [get_ports {led}]
#set_property PACKAGE_PIN E19 [get_ports {count[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
#set_property PACKAGE_PIN U19 [get_ports {count[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
#set_property PACKAGE_PIN V19 [get_ports {count[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
#set_property PACKAGE_PIN W18 [get_ports {LED[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
#set_property PACKAGE_PIN U15 [get_ports {LED[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
#set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
#set_property PACKAGE_PIN V14 [get_ports {LED[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
#set_property PACKAGE_PIN V13 [get_ports {LED[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
#set_property PACKAGE_PIN V3 [get_ports {LED[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
#set_property PACKAGE_PIN W3 [get_ports {LED[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
#set_property PACKAGE_PIN U3 [get_ports {LED[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
#set_property PACKAGE_PIN P3 [get_ports {LED[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
#set_property PACKAGE_PIN N3 [get_ports {LED[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
#set_property PACKAGE_PIN P1 [get_ports {LED[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
#set_property PACKAGE_PIN L1 [get_ports {LED[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
